---
extends: default

rules:
  indentation:
    spaces: 2
    indent-sequences: consistent

  line-length:
    max: 120

  truthy:
    allowed-values: ["true", "false"]
    check-keys: true

  comments:
    min-spaces-from-content: 1
