---
- name: Grub mkconfig
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  become: true
  changed_when: true
  when: ansible_os_family == "Debian"
  notify: Reboot system

- name: Reboot system
  ansible.builtin.reboot:
  become: true
