---
- name: Include OS specific variables
  ansible.builtin.include_vars:
    "{{ ansible_os_family }}.yaml"

- name: Install OS specific KVM packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 5
  loop: "{{ kvm_related_packages | flatten(levels=1) }}"

- name: Include task swappiness.yaml
  ansible.builtin.include_tasks:
    file: swappiness.yaml

- name: Include task kernel_tuning.yaml
  ansible.builtin.include_tasks:
    file: iommu.yaml
