---
kvm_host: kvm-dev
cluster_name: k8s-dev
image_pool_dir: /var/lib/libvirt/images
timezone: Europe/Helsinki
network:
  domainName: "{{ cluster_name }}.local"
  ipv4Address: 192.168.152.0
  ipv4_gateway: 192.168.152.1
  ipv4_mask: 255.255.255.0
storage_pools:
  - pool:
      name: pool1
      path: /var/lib/libvirt/filesystems/pool1
  - pool:
      name: pool2
      path: /var/lib/libvirt/filesystems/pool2
  - pool:
      name: pool3
      path: /var/lib/libvirt/filesystems/pool3
base_image_checksum: # updated 2023-12-02
  sha512:8ae6f0e1be8ce01e1fd4cd883c2ba5d08c550c2aa13b32fa1f24c8cca44e596a197146223b90d84544997a4ba932c99de90e2ce5b1cc3504559066d1d28d630b
base_image_name: debian-11-genericcloud-amd64.qcow2
base_image_url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2
masters:
  - disk_size: 100G
    ipv4: 192.168.152.11/24
    name: node1
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/pool1
    ram_mb: 12288
    vcpus: '2'
workers:
  - disk_size: 150G
    ipv4: 192.168.152.21/24
    name: node4
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/pool1
    ram_mb: 24576
    vcpus: '2'
  - disk_size: 150G
    ipv4: 192.168.152.22/24
    name: node5
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/pool2
    ram_mb: 24576
    vcpus: '2'
  - disk_size: 150G
    ipv4: 192.168.152.23/24
    name: node6
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/pool3
    ram_mb: 24576
    vcpus: '2'
